SEED: 42
EXP_NAME: grace_cub_actor_critic

MODEL:
  NAME: "grace_cbm"
  N_CONCEPTS: 955
  BOOL_CONCEPTS: False

DATASET:
  NAME: cub
  ROOT: ../../datasets
  N_TASKS: 200
  N_CONCEPTS: 955
  IMG_SIZE: 299
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  CONCEPT_SOURCE: pseudo
  PSEUDO_DIR: ./pseudo_concept_gt
  PSEUDO_TYPE: soft
  PSEUDO_TOPK: 20

GRACE:
  K: 256

  STAGE1_EPOCHS: 100
  STAGE2_EPOCHS: 40
  STAGE3_EPOCHS: 20

  FULL_Y_WEIGHT: 1.0
  SEL_Y_WEIGHT: 0.1

  ENTROPY_COEF: 5.0e-2
  ENTROPY_COEF_END: 5.0e-3
  ENTROPY_ANNEAL_EPOCHS: 50

  VALUE_COEF: 0.5
  ADV_EPS: 1.0e-6
  REWARD_EMA_MOMENTUM: 0.95

  ACTOR_LR: 3.0e-5
  CRITIC_LR: 1.0e-4

  ACTOR_HIDDEN_DIM: 512
  CRITIC_HIDDEN_DIM: 256
  ACTOR_DROPOUT: 0.0
  CRITIC_DROPOUT: 0.0

  CONCEPT_ACC_THRESHOLD: 0.5
  MAX_GRAD_NORM: 5.0

TRAIN:
  EPOCHS: 300
  BATCH_SIZE: 128
  NUM_WORKERS: 4
  C_LOSS_WEIGHT: 5.0
  Y_LOSS_WEIGHT: 1.0
  IMBALANCE: false
  PATIENCE: 15

  OPTIM:
    NAME: sgd
    LR: 0.01
    MOMENTUM: 0.9
    WD: 4.0e-5

  SCHEDULER:
    NAME: lrp

VAL:
  BATCH_SIZE: 64
  NUM_WORKERS: 2
  FREQUENCY: 5

TEST:
  BATCH_SIZE: 64
  NUM_WORKERS: 2